const users = [
  {
    name: 'Airyque Ervin',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AE.jpg',
    location: 'Miami, FL',
    friends: 103,
    reviews: 27,
  },
  {
    name: 'Andy Nguyen',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AN.jpg',
    location: 'Austin, TX',
    friends: 57,
    reviews: 3,
  },
  {
    name: 'Angel Hernandez',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AH.jpg',
    location: 'San Francisco, CA',
    friends: 309,
    reviews: 90,
  },
  {
    name: 'Arjun Chemparathy',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/AC.jpg',
    location: 'New York, NY',
    friends: 79,
    reviews: 21,
  },
  {
    name: 'Beth Johnson',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/BJ.png',
    location: 'Cleveland, OH',
    friends: 289,
    reviews: 11,
  },
  {
    name: 'Javier Enriquez',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/JE.jpg',
    location: 'Los Angeles, CA',
    friends: 131,
    reviews: 34,
  },
  {
    name: 'Josh Alamillo',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/JA.jpg',
    location: 'Boston, MA',
    friends: 77,
    reviews: 6,
  },
  {
    name: 'Josh Glandorf',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/JG.jpg',
    location: 'Tokyo, Japan',
    friends: 182,
    reviews: 58,
  },
  {
    name: 'Kevin Share',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/KS.jpg',
    location: 'Orlando, FL',
    friends: 99,
    reviews: 13,
  },
  {
    name: 'Makan Azarshahy',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MA.jpg',
    location: 'Portland, OR',
    friends: 562,
    reviews: 194,
  },
  {
    name: 'Mark Kuba',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MK.jpg',
    location: 'Raleigh, NC',
    friends: 134,
    reviews: 20,
  },
  {
    name: 'Mat Bagnall',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MB.jpg',
    location: 'Auckland, New Zealand',
    friends: 196,
    reviews: 17,
  },
  {
    name: 'Matt Mullen',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MM.jpg',
    location: 'Desert, NV',
    friends: 58,
    reviews: 39,
  },
  {
    name: 'Michael Durfey',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MD.jpg',
    location: 'San Diego, CA',
    friends: 107,
    reviews: 18,
  },
  {
    name: 'Michael Ngo',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/MN.jpg',
    location: 'St. Louis, MO',
    friends: 112,
    reviews: 4,
  },
  {
    name: 'Namson Leung',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/NL.jpg',
    location: 'Seattle, WA',
    friends: 90,
    reviews: 2,
  },
  {
    name: 'Nicholas Peyrichou',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/NP.jpg',
    location: 'New Orleans, LA',
    friends: 156,
    reviews: 71,
  },
  {
    name: 'Philip Lee',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/PL.jpg',
    location: 'Sacramento, CA',
    friends: 80,
    reviews: 32,
  },
  {
    name: 'Sara Brandes',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/SB.jpg',
    location: 'Berkeley, CA',
    friends: 169,
    reviews: 17,
  },
  {
    name: 'Shaital Desai',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/SD.jpg',
    location: 'Las Vegas, NV',
    friends: 193,
    reviews: 37,
  },
  {
    name: 'Wayman Ng',
    photo: 'https://s3-us-west-1.amazonaws.com/foodigouserphotos/WN.jpg',
    location: 'Salt Lake City, UT',
    friends: 124,
    reviews: 48,
  },
];

module.exports = users;
